config/routes.rb
Rails.application.routes.draw do
  get 'attachment/pdf'

  resources :companies

  get 'home/index'

 devise_for :users, :controllers => { :registrations => 'registrations'},:path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "users"

  get "customer_lookups/list_all" => "customer_lookups#list_all"
  get "customer_lookups/search" => "customer_lookups#search"
  get "pending_approve/list_all" => "pending_approve#list_all"
  
  root to: "home#index"
  
  resources :users

resources :companies do
    resources :certificates do
       member do
        get :issue_license,:as => 'issue_license' 
        get :ready_approval,:as => 'ready_approval' 
      end
    end
    resources :attachments,:only => :pdf  do
      member do
        get :pdf,:as => 'pdf'
      end  
    end
    resources :owners,:only => [:passport_pdf,:national_pdf]  do
      member do
        get :passport_pdf,:as => 'passport_pdf'
        get :national_pdf,:as => 'national_pdf'
      end  
    end
  end

  match '*a' => 'errors#routing' ,:via => [:get,:post,:delete,:patch,:post]

end

app/models/company.rb
class Company < ActiveRecord::Base

	validates :name, presence: true
	validates :address, presence: true
	
	has_many :owners, :dependent => :destroy
	accepts_nested_attributes_for :owners, :allow_destroy => true
	has_many :attachments, :dependent => :destroy
	accepts_nested_attributes_for :attachments, :allow_destroy => true
	has_many :certificates, :dependent => :destroy
	accepts_nested_attributes_for :certificates, :allow_destroy => true
	after_save ThinkingSphinx::RealTime.callback_for(:company)
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  respond_to :html

  def index

    if current_user.has_role? :staff
     @companies = Company.all
    elsif current_user.has_role? :director
    @companies = Company.joins(:certificates).where.not(:certificates => {workflow_state: ['inititated','pending']})
     elsif current_user.has_role? :minister
    @companies = Company.joins(:certificates).where.not(:certificates => {workflow_state: ['inititated','pending','awaiting_for_director_approval']})
    else
    @companies = Company.all
    end 

    respond_to do |format|
      format.html 
    end  
  end

  def show
   # respond_with(@company)
     @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  def new
    @company = Company.new
    #respond_with(@company)
    #@project = Project.new
    1.times do
      @company.owners.build
      @company.attachments.build
      @company.certificates.build
    end
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)
    #@company.save
    #respond_with(@company)
    #@project = Project.new(params[:project])
    puts @company.certificates.first.user_id = current_user.id
    respond_to do |format|
      if @company.save
        @company.certificates.first.submit!
        @company.certificates.first.license_issue_code = "WHG#{@company.certificates.first.id}"
        @company.certificates.first.save
        #format.html { redirect_to(@company, :notice => 'Project was successfully created.') }
        format.html { redirect_to(company_certificate_path(@company,@company.certificates.first), :notice => 'Certficate was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end


 def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(company_params)
        #format.html { redirect_to(@company, :notice => 'Project was successfully updated.') }
        format.html { redirect_to(company_certificate_path(@company,@company.certificates.first), :notice => 'Certficate was successfully created.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destroy
   # @company.destroy
   # respond_with(@company)
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
  end
end
  def approve

  end
  
  def reject

  end
   
  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      #params.require(:company).permit(:name, :address, attachments_attributes:[ :_destroy, :id, :attachment ], owners_attributes: [:id, :name, :_destroy, national_proof_attributes: [:id, :national_id, :_destroy], passport_proof_attributes: [:id, :passport_no, :_destroy]] )
      params.require(:company).permit(:name, :address, attachments_attributes:[ :_destroy, :id, :attachment, :description ], owners_attributes: [:id, :name, :_destroy, :passport_attachment,:national_attachment,:phone,:nationality,:email,:gender,:birth_date,:national_id,:passport_number,:national_id_expiry_date,:passport_number_expiry_date ],certificates_attributes:[ :_destroy, :id, :cert_issue_date,:cert_eff_date,:cert_term_date, :description ] )
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_attachment_fields.html.erb
<div class="nested-fields">
  <%= f.inputs do %>
  <div class="row">
    <div class="span5">  
       <div class="input-control select size4">
        <%= f.select :description, options_for_select([["Authorization/Business receipt", "Authorization/Business receipt"],["Bank Statement","Bank Statement"],["Heshiiska Milkilayaasha/Letter or Owner of Agreement", "Heshiiska Milkilayaasha/Letter or Owner of Agreement"],["Receipts","Receipts"],["Other","Other"]],
                  :selected => f.object.description) %>
        </div>          
      <div class="file size8">
        <table>
          <tr>
              <td valign="middle">
                  <%= f.file_field :attachment %>
              </td>  
               <%  unless f.object.attachment.url(:thumb).include? "missing" %>  
              <td valign="top">
                 <a href="<%=f.object.attachment.url(:retina)%>" rel="hermitage">
                     <%=f.template.image_tag(f.object.attachment.url(:thumb)) %>
                  </a>
               </td>
               <% end %>
               <td valign="top">
                 <%= link_to_remove_association "Remove Attachment", f,:class=>"medium button danger default" %>
               </td>
            </tr>
           </table>        
      </div>
    </div>
  </div>
        <% end %>
</div>

app/views/companies/_form.html.erb
<%= semantic_form_for @company, :html => { :multipart => true,:class => "form-horizontal" }  do |f| %>
<% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:" %>
      </h2>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <legend>Magaca Shirkada / New Business Information</legend>
  <div class="row">
    <div class="span5">  
      <label>Magaca Shirkada/Company Name</label>
      <div class="input-control text size4" data-role="input-control">
        <%= f.text_field  :name,:placeholder=>"Magaca Shirkada/Company Name",:required => true %>
        <button class="btn-clear" tabindex="-1"></button>
      </div>
  </div>
  <div class="span5">  
    <label>Ciwaan/Address</label>
    <div class="input-control textarea size4" data-role="input-control">
       <%= f.text_area :address, :as => :text, :input_html => { :rows => 4, :cols => 20 },
       :placeholder=>"Ciwaan/Address",:required => true %>
    </div>
  </div>
</div>
</fieldset>

  <fieldset>
    <legend>Shaqsiga Magaciisa/ Business Owners Information</legend>
    <div>  
      <%= f.semantic_fields_for :owners do |owner| %>
        <%= render 'owner_fields', :f => owner %>
      <% end %>
        <div> 
          <br/>
      <%= link_to_add_association 'Shaqsiga Magaciisa/Add Business Owner', f, :owners, :class=>"info medium button"  %>
        </div> 
    </div>
  </fieldset>
<br/>
<br/>
  <fieldset>
    <legend>Common  Required Documents Intake</legend>
     <div>  
     <%= f.semantic_fields_for :attachments do |attachment| %>
        <%= render 'attachment_fields', :f => attachment %>
    <% end %> 
    <div> 
      <br/>
      <%= link_to_add_association 'Add Attachment', f, :attachments,:class=>"info medium button" %>
     </div>  
    </div>   
 </fieldset> 
 
<br/>
<br/>
  <fieldset>
    <legend>Shaqsiga Magaciisa/ License Information</legend>
    <div>  
      <%= f.semantic_fields_for :certificates do |certificate| %>
        <%= render 'certificates/form', :f => certificate %>
      <% end %>
        <div> 
          <br/>
   
        </div> 
    </div>
  </fieldset>

  <input name="commit" class="success large" data-disable-with="Please wait processing." type="submit" value="Update Business Information Form">


                
<% end %>


         


app/views/companies/_national_proof_fields.html.erb
<div class="nested-fields">
  <%= f.inputs do %>
    <div class="form-group">
    <label class="col-md-2" for="textinput">National ID</label>  
      <div class="col-md-3">
          <%= f.text_field  :national_id,:class => "form-control input-md" %>
      </div>
      <div class="links col-md-2">
      <%= label_tag '' %>
      <%= link_to_remove_association "remove National ID", f,:class=>"btn btn-default" %>
    </div>
	</div>
  <% end %>
</div>

app/views/companies/_passport_proof_fields.html.erb
<div class="nested-fields">
	<%= f.inputs do %>
	<div class="form-group">
      <label class="col-md-2" for="textinput">Passport No.</label>  
      <div class="col-md-3">
          <%= f.text_field  :passport_no,:class => "form-control input-md" %>
      </div>
     <div class="links col-md-2">
      <%= label_tag '' %>
      <%= link_to_remove_association "remove Passport", f,:class=>"btn btn-default" %>
    </div>
</div>
  <% end %>
</div>
 

app/views/companies/_show.html.erb
                <table class="table">
                   <tr class="info">
                      <td class="text-left" colspan="4">
                         Business Information
                       </td>   
                    </tr>  
                    <tr>
                      <td class="text-left span4">
                         Company Name:
                       </td>   
                       <td class="text-left span3">
                          <%= @company.name %>
                       </td> 
                       <td class="text-left span3">
                         Address:
                       </td>   
                       <td class="text-left span3">
                         <%= @company.address %>
                       </td>   
                     </tr>   
                     <tr class="info">
                      <td class="text-left" colspan="4">
                         Owners Information
                       </td>   
                    </tr>   
                     <% @company.owners.each do |owner| %>
                        <tr>
                          <td class="text-left">
                             Owner Name:
                           </td>   
                           <td class="text-left">
                               <%= owner.name %>
                           </td> 
                           <td class="text-left">
                              Birth Date:
                           </td>   
                           <td class="text-left">
                                <%= owner.birth_date.to_date.strftime('%v') %>
                           </td>  
                         </tr>  
                         <tr>
                          <td class="text-left">
                             Nationality:
                           </td>   
                           <td class="text-left">
                                <%= owner.nationality %>
                           </td>  

                          <td class="text-left">
                              Gender:
                           </td>   
                           <td class="text-left">
                                 <%= owner.gender %>
                            </td>  
                          </tr>
                          <tr>  
                             <td class="text-left">
                                Email:
                             </td>   
                             <td class="text-left">
                                   <%= owner.email %>
                              </td>  
                              <td colspan="4">
                                &nbsp;
                              </td>
                         </tr> 
                         <tr>
                            <td class="text-left">
                                National ID<br/>
                                Expiry Date:
                             </td>   
                             <td class="text-left">
                                  <%= owner.national_id %><br/>
                                   <%= owner.national_id_expiry_date.to_date.strftime('%v') %>
                              </td>  
                            <td class="text-left">
                                National ID Attachment:
                             </td>   
                             <td class="text-left">
                                   <a href="<%=owner.national_attachment.url(:retina)%>" rel="hermitage">
                                    <%= image_tag owner.national_attachment.url(:thumb) %>
                                  </a>
                                  <% if owner.national_attachment.content_type == 'application/pdf' %>
                                    <%= link_to "Download pdf", national_pdf_company_owner_path(@company,owner) %>
                                  <% end %>     
                              </td>  
                         </tr> 
                         <tr>
                              <td class="text-left">
                               Passport Number:<br/>
                               Passport Expiry Date:
                             </td>   
                             <td class="text-left">
                                   <%= owner.passport_number %><br/>
                                   <%= owner.passport_number_expiry_date.to_date.strftime('%v') %>
                              </td>  
                              <td class="text-left">
                                Passport Attachment:
                             </td>   
                             <td class="text-left">
                                  <a href="<%=owner.passport_attachment.url(:retina) %>" rel="hermitage">
                                    <%= image_tag owner.passport_attachment.url(:thumb) %>
                                  </a>
                                  <% if owner.passport_attachment.content_type == 'application/pdf' %>
                                    <%= link_to "Download pdf", passport_pdf_company_owner_path(@company,owner) %>
                                  <% end %>     
                              </td>  
                         </tr>  
                        <% end %>   
                      <tr class="info">
                        <td class="text-left" colspan="4">
                            Other Attachments
                         </td>   
                       </tr>   
       
                   
                        <% @company.attachments.each do |attachment| %>
                          <tr>
                              <td class="text-left">
                                  <%= attachment.description%>:
                               </td>   
                               <td class="text-left span4" colspan="3">
                                      <a href="<%=attachment.attachment.url(:retina)%>" rel="hermitage">
                                       <%= image_tag attachment.attachment.url(:thumb) %>
                                      </a>
                                  <% if attachment.attachment.content_type == 'application/pdf' %>
                                    <%= link_to "Download pdf", pdf_company_attachment_path(@company,attachment) %>
                                  <% end %>  
                                </td>  
                           </tr> 
                          <% end %>  
                 </table>   
 

app/views/companies/edit.html.erb
<div class="row">
			<div class="span12 padding5">
				<div class="span3">
					
				<nav class="sidebar light">
    <ul>
        <li class="title">Admin Section</li>
        <li class="stick" data-no-turbolink >
        <%= link_to(companies_path) do %>
          <i class="icon-arrow-left"></i>Dashboard</a>
         <% end %> 
       </li>
         <li class="stick">
         <%= link_to(new_company_path) do %>
           <i class="icon-new"></i> Client Registration
          <% end %>
        </li>
  
        <li class="stick"><a href="#"><i class="icon-newspaper"></i>Expired Certificates</a></li>
        <li class="stick"><a href="/pending_approve/list_all"><i class="icon-enter"></i>Pending To Approve</a></li>
    <li class="stick"><a href="#"><i class="icon-printer"></i>Print Actions</a></li>
    <li class="stick"><a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a></li>
    </ul>
</nav>
					
				</div>
				<div class="span9">
					<div class="panel">
							<div class="panel-content">
									<%= render 'form' %>
								
		      </div>
            </div>
        </div>
        </div>
      </div>

app/views/companies/index.html.erb
<div class="row">
  <div class="span12 ">
  <nav class="navigation-bar compact">
  <div class="navigation-bar-content">
   <% if  current_user.has_role? :staff  %>   
        <%= link_to new_company_path, :class=>'element' do %>
         <i class="icon-new"></i> Client Registration
        <% end %>  
         <span class="element-divider"></span>
    <% end %>       
  <% if can? :manage, current_user %>
     <%= link_to users_path, :class=>'element' do %>
          <i class="icon-user-3"></i>Manage Users
      <% end %>
    <span class="element-divider"></span>
   <% end %> 
    <% if can? :manage, current_user %>
           <%= link_to new_user_registration_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Add Users
            <% end %>
  <span class="element-divider"></span>
    <% end %>  
     <% if can? :manage, current_user %>
           <%= link_to edit_user_registration_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Change Password
            <% end %>
   <% end %>  
          
      <span class="element-divider"></span>
      <a href="#" class="element"><i class="icon-newspaper"></i>Expired Licenses</a>
      <span class="element-divider"></span>
      <a href="pending_approve/list_all" class="element"><i class="icon-enter"></i>Pending To Approve</a>
      <span class="element-divider"></span>
      <a href="#" class="element"><i class="icon-printer"></i>Print Actions</a>
      <span class="element-divider"></span>
      <a href="customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a>
  </div>
 </nav>
  
</div>
<div class="row">
  <div class="span12 padding10">
    <div class="panel">
        <div class="panel-content">
          <table id="products" class="display">
                <thead>
                  <tr>
                      <th class="text-left">Company Name </th>
                      <th class="text-left">License Activity</th>
                      <th class="text-left">Status</th>
                      <th class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <%@companies.each do |company| %>  
                    <% if !company.certificates.present? %>
                      <tr>
                          <td><%= company.name %></td>
                          <td class="right">&nbsp;</td>
                          <td class="right">&nbsp;</td>
                          <td class="right" >
                             <div class="row">
                            <% if can? :read, company %>
                              <div class="span6">
                               <%= link_to(company) do %>
                                  <button class="small info">View Business</button>
                                <% end %>
                               </div> 
                            <% end %>
                            <% if can? :update, company %>
                              <div class="span6">
                                <%= link_to(edit_company_path(company)) do %>
                                  <button class="small default">Edit Business</button>
                                <% end %>
                              </div>
                              <% end %>
                             </div>
                             <div class="row">  
                            <%= link_to(new_company_certificate_path(company)) do %>
                              <%@clss = company.certificates.first.present? ? "small success" : "small warning"%>
                              <button class= "<%=@clss%>" data-no-turbolink >Add License</button>
                            <% end %>
                          </div>
                        </td>
                      </tr>
                    <% end %>  
                    <% company.certificates.each do |certificate| %>  
                      <tr>
                          <td><%= company.name %></td>
                          
                          <td class="right"><%= certificate.description %>
                        
                            
                            
                          </td>
                          
                           
                          
                          <td class="right">
                             <% if !certificate.workflow_state.nil? %>
                                 <%= certificate.workflow_state.gsub(/_/, " ") %>
                             <% end %>
                          </td>
                          <td class="right" >
                            <!--<div class="row">
                               <% if can? :read, company %>
                                  <div class="span6">
                                     <%= link_to(company) do %>
                                        <button class="small info">View Business</button>
                                      <% end %>
                                    </div> 
                                <% end %>

                                <% if can? :update, company %>
                                    <div class="span6">
                                       <%= link_to(edit_company_path(company)) do %>
                                        <button class="small default">Edit Business</button>
                                      <% end %>
                                    </div>  
                                <% end %>
                            </div>-->

                            <div align="center">
                                  <div class="span3">
                                      <%= link_to(company_certificate_path(company,certificate)) do %>
                                        <button class= "small success" data-no-turbolink >View</button>
                                      <% end %>
                                    </div> 
                                  <% if !can? :manage, certificate and certificate.license_issued? and can? :issue, certificate %>
                                    <div class="span4">
                                       <%= link_to(company_certificate_path(company,certificate,:pdf )) do %>
                                        <button class="small info">Download</button>
                                      <% end %>
                                    </div>  
                                <% end %>

                                  <% if !certificate.license_issued? and  (current_user.has_role? :staff)  and can? :update, company %>
                                    <div class="span3">
                                       <%= link_to(edit_company_path(company)) do %>
                                        <button class="small default">Edit</button>
                                      <% end %>
                                    </div>  
                                <% end %>
                                <% if certificate.minister_has_accepted? or certificate.reinstated? %> 
                                   <% if current_user.has_role? :staff and can? :issue, certificate %>
                                        <div class="span3">
                                            <%= link_to(issue_license_company_certificate_path(company,certificate)) do %>
                                              <button class= "small success" data-disable-with="Processing."  data-no-turbolink >Issue</button>
                                            <% end %>
                                          </div> 
                             <% end %>
                                  <!--  <div class="span6">
                                      <%= link_to(edit_company_certificate_path(company,certificate)) do %>
                                        <button class="small default">Edit License</button>
                                      <% end %>
                                    </div>  -->
                            </div>

                     


                                 <% end %> 
                  </td>
                </tr>
                      <%end%>

                  <%end%>
                </tbody>
              </table>
        </div>
      </div>
  </div>
  </div>

app/views/companies/new.html.erb
<div class="row">
			<div class="span12 padding5">
				<div class="span3">
					
				<nav class="sidebar light">
    <ul>
        <li class="title">Admin Section</li>
        <li class="stick">
         <%= link_to(companies_path) do %>
           <i class="icon-new"></i> Dashboard
          <% end %>
        </li>
        <li class="stick"><a href="#"><i class="icon-newspaper"></i>Expired Certificates</a></li>
        <li class="stick"><a href="/pending_approve/list_all"><i class="icon-enter"></i>Pending To Approve</a></li>
    <li class="stick"><a href="#"><i class="icon-printer"></i>Print Actions</a></li>
    <li class="stick"><a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a></li>
    </ul>
</nav>
					
				</div>
				<div class="span9">
					<div class="panel">
							<div class="panel-content">
									<%= render 'form' %>
                </div>
            </div>
          </div>
        </div>
      </div>

app/views/companies/show.html.erb
<div class="row">
      <div class="span12 padding5">
        <div class="span3">
          
        <nav class="sidebar light">
    <ul>
        <li class="title">Admin Section</li>
        <li class="stick" data-no-turbolink >
        <%= link_to(companies_path) do %>
          <i class="icon-arrow-left"></i>Back</a>
         <% end %> 
       </li>
        <li class="stick">
         <%= link_to(edit_company_path(@company)) do %>
           <i class="icon-wrench"></i> Edit Application Form
          <% end %>
        </li>
        <li class="stick"><a href="#"><i class="icon-home"></i>Client Registration</a></li>
        <li class="stick"><a href="#"><i class="icon-newspaper"></i>Expired Certificates</a></li>
        <li class="stick"><a href="/pending_approve/list_all"><i class="icon-enter"></i>Pending To Approve</a></li>
    <li class="stick"><a href="#"><i class="icon-printer"></i>Print Actions</a></li>
    <li class="stick"><a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a></li>
    </ul>
</nav>
          
        </div>
        <div class="span9">
          <div class="panel">
              <div class="panel-content">
                 <%= render  "show" %>

  
                </div>
            </div>
          </div>
        </div>
      </div>

                 