config/routes.rb
Rails.application.routes.draw do
  get 'attachment/pdf'

  resources :companies

  get 'home/index'

 devise_for :users, :controllers => { :registrations => 'registrations'},:path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "users"

  get "customer_lookups/list_all" => "customer_lookups#list_all"
  get "customer_lookups/search" => "customer_lookups#search"
  get "pending_approve/list_all" => "pending_approve#list_all"
  
  root to: "home#index"
  
  resources :users

resources :companies do
    resources :certificates do
       member do
        get :issue_license,:as => 'issue_license' 
        get :ready_approval,:as => 'ready_approval' 
      end
    end
    resources :attachments,:only => :pdf  do
      member do
        get :pdf,:as => 'pdf'
      end  
    end
    resources :owners,:only => [:passport_pdf,:national_pdf]  do
      member do
        get :passport_pdf,:as => 'passport_pdf'
        get :national_pdf,:as => 'national_pdf'
      end  
    end
  end

  match '*a' => 'errors#routing' ,:via => [:get,:post,:delete,:patch,:post]

end

app/controllers/customer_lookups_controller.rb
class CustomerLookupsController < ApplicationController
  before_filter :authenticate_user!


	def search
	    respond_to do |format|
	      format.html
	    end 
	end

	def list_all
		@data = search_by_sphinx(params[:search_company_id], params[:search_owner_name], params[:search_company_name])
	    respond_to do |format|
	      format.html
	    end 
	end

	private

	def search_by_sphinx(company_id, owner_name, company_name)
		owners_by_name 	  = search_by_owner_name(owner_name)
		owners_by_company = search_by_company_name(company_name)
		owner_by_id 	  = search_by_company_id(company_id)

		final_results = owners_by_name + owners_by_company + owner_by_id
		final_results.uniq
	end


	def search_by_query(company_id, owner_name, company_name)
		if (company_id.blank?)
			sql_query = "select distinct cmp.id as CompanyId, own.name as OwnerName,cmp.name as CompanyName, cer.description as CerDescription,lia1.status as CerStatus,DATE_FORMAT(lia1.updated_at,'%m-%d-%Y %h:%i %p') as CertLastActivity from owners own 
                    inner join companies cmp on own.company_id=cmp.id 
                    inner join certificates cer on cer.company_id=own.company_id 
                    inner join  license_issue_activities lia1 on lia1.certificate_id=cer.id 
                    inner join  license_issue_activities lia2 on lia1.certificate_id=lia2.certificate_id 
                    where  own.name LIKE '%#{owner_name}%' and cmp.name LIKE '%#{company_name}%'
                    GROUP BY cmp.id,own.name,cmp.name,cer.description,lia1.status,lia1.updated_at  
                    HAVING lia1.updated_at=MAX(lia2.updated_at)
                    ORDER BY cmp.id,own.name,cmp.name,cer.description,lia1.status"
        else
        	sql_query = "select distinct cmp.id as CompanyId, own.name as OwnerName,cmp.name as CompanyName, cer.description as CerDescription,lia1.status as CerStatus,DATE_FORMAT(lia1.updated_at,'%m-%d-%Y %h:%i %p') as CertLastActivity from owners own 
                    inner join companies cmp on own.company_id=cmp.id 
                    inner join certificates cer on cer.company_id=own.company_id 
                    inner join  license_issue_activities lia1 on lia1.certificate_id=cer.id 
                    inner join  license_issue_activities lia2 on lia1.certificate_id=lia2.certificate_id 
                    where  cmp.id='#{company_id}' and own.name LIKE '%#{owner_name}%' and cmp.name LIKE '%#{company_name}%'
                    GROUP BY cmp.id,own.name,cmp.name,cer.description,lia1.status,lia1.updated_at 
                    HAVING lia1.updated_at=MAX(lia2.updated_at)
                    ORDER BY cmp.id,own.name,cmp.name,cer.description,lia1.status"
		end
		#results = ActiveRecord::Base.connection.exec_query(sql_query).rows
		results = ActiveRecord::Base.connection.select_all(sql_query).to_a
	end

	def search_by_company_name(company_name)
		companies = Company.search (company_name) unless company_name.blank?
		ids = companies.map(&:id) unless company_name.blank?
		owners = Owner.where(:company_id => ids) unless ids.blank?
		owners.blank? ? [] : owners.to_a
	end

	def search_by_owner_name(owner_name)
		owner = Owner.search (owner_name) unless owner_name.blank?
		owner.blank? ? [] : owner
	end

	def search_by_company_id(company_id)
		comp = Company.find_by_id(company_id) unless company_id.blank?
		owner = Owner.where(:company_id => comp.id) unless comp.blank?
		owner.blank? ? [] : owner.to_a
	end
end

app/views/customer_lookups/list_all.html.erb
<div class="row">
  <div class="span12 ">
    <nav class="navigation-bar compact">
      <div class="navigation-bar-content">
        <% if  current_user && current_user.has_role?("staff") %>
            <%= link_to new_company_path, :class=>'element' do %>
                <i class="icon-new"></i> Client Registration
            <% end %>
            <span class="element-divider"></span>
        <% end %>
        <% if can? :manage, current_user %>
            <%= link_to users_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Manage Users
            <% end %>
            <span class="element-divider"></span>
        <% end %>
        <% if can? :manage, current_user %>
            <%= link_to new_user_registration_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Add Users
            <% end %>
            <span class="element-divider"></span>
        <% end %>
        <% if can? :manage, current_user %>
            <%= link_to edit_user_registration_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Change Password
            <% end %>
        <% end %>

        <span class="element-divider"></span>
        <a href="#" class="element"><i class="icon-newspaper"></i>Expired Licenses</a>
        <span class="element-divider"></span>
        <a href="/pending_approve/list_all" class="element"><i class="icon-enter"></i>Pending To Approve</a>
        <span class="element-divider"></span>
        <a href="#" class="element"><i class="icon-printer"></i>Print Actions</a>
        <span class="element-divider"></span>
        <a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a>
      </div>
    </nav>

  </div>
<div style="padding-top: 78px;" align="center" >
	<%= form_tag(customer_lookups_list_all_path, :method => "get", id: "search-form") do %>
	  Company Id  <%= text_field_tag :search_company_id, params[:search_company_id], placeholder: "company_id"%>
	  Owner Name  <%= text_field_tag :search_owner_name, params[:search_owner_name], placeholder: "owner_name"%>
	  Company Name  <%= text_field_tag :search_company_name, params[:search_company_name], placeholder: "company_name"%>
	  <%= submit_tag "Search", :name => nil %>
	<% end %>
</div>

  <div class="row">
    <div class="span12 padding10">
      <div class="panel">
        <div class="panel-content">
          <table id="products" class="display">
                <thead>
                  <tr>
                      <th class="text-left">CompanyId</th>
                      <th class="text-left">OwnerName</th>
                      <th class="text-left">CompanyName</th>
                      <th class="text-center">CerDescription</th>
                      <th class="text-center">CerStatus</th>
                      <th class="text-center">CertLastActivity</th>
                  </tr>
                </thead>
                <tbody>
                  <%@data.each do |row| %>  
                      <tr>
                          <td class="right"><%= row.company_id %></td>
                          <td class="right"><%= row.name %></td>
                          <td class="right"><%= row.company.name %></td>
                          <td class="right"><%= row.company.certificates.last.description %></td>
                          <td class="right"><%= row.company.certificates.last.license_issue_activities.last.status %></td>
                          <td class="right"><%= row.company.certificates.last.license_issue_activities.last.updated_at.strftime("%d/%m/%y %H:%M") %></td>
                      </tr>
                  <%end%>
                </tbody>
              </table>
        </div>
      </div>
  </div>
  </div>
</div>
  </div>

<style>
  #products_length, #products_filter{
      display: none;
  }
</style>

app/views/customer_lookups/search.html.erb
<div class="row">
  <div class="span12 ">
    <nav class="navigation-bar compact">
      <div class="navigation-bar-content">
        <% if  current_user.has_role? :staff  %>
            <%= link_to new_company_path, :class=>'element' do %>
                <i class="icon-new"></i> Client Registration
            <% end %>
            <span class="element-divider"></span>
        <% end %>
        <% if can? :manage, current_user %>
            <%= link_to users_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Manage Users
            <% end %>
            <span class="element-divider"></span>
        <% end %>
        <% if can? :manage, current_user %>
            <%= link_to new_user_registration_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Add Users
            <% end %>
            <span class="element-divider"></span>
        <% end %>
        <% if can? :manage, current_user %>
            <%= link_to edit_user_registration_path, :class=>'element' do %>
                <i class="icon-user-3"></i>Change Password
            <% end %>
        <% end %>

        <span class="element-divider"></span>
        <a href="#" class="element"><i class="icon-newspaper"></i>Expired Licenses</a>
        <span class="element-divider"></span>
        <a href="/pending_approve/list_all" class="element"><i class="icon-enter"></i>Pending To Approve</a>
        <span class="element-divider"></span>
        <a href="#" class="element"><i class="icon-printer"></i>Print Actions</a>
        <span class="element-divider"></span>
        <a href="customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a>
      </div>
    </nav>

  </div>

<div style="padding-top: 78px;" align="center" >
	<%= form_tag(customer_lookups_list_all_path, :method => "get", id: "search-form") do %>
	  Company Id  <%= text_field_tag :search_company_id, params[:search_company_id], placeholder: "company_id"%>
	  Owner Name  <%= text_field_tag :search_owner_name, params[:search_owner_name], placeholder: "owner_name"%>
	  Company Name  <%= text_field_tag :search_company_name, params[:search_company_name], placeholder: "company_name"%>
	  <%= submit_tag "Search", :name => nil %>
	<% end %>
</div>

 </div>