config/routes.rb
Rails.application.routes.draw do
  get 'attachment/pdf'

  resources :companies

  get 'home/index'

 devise_for :users, :controllers => { :registrations => 'registrations'},:path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "users"

  get "customer_lookups/list_all" => "customer_lookups#list_all"
  get "customer_lookups/search" => "customer_lookups#search"
  get "pending_approve/list_all" => "pending_approve#list_all"
  
  root to: "home#index"
  
  resources :users

resources :companies do
    resources :certificates do
       member do
        get :issue_license,:as => 'issue_license' 
        get :ready_approval,:as => 'ready_approval' 
      end
    end
    resources :attachments,:only => :pdf  do
      member do
        get :pdf,:as => 'pdf'
      end  
    end
    resources :owners,:only => [:passport_pdf,:national_pdf]  do
      member do
        get :passport_pdf,:as => 'passport_pdf'
        get :national_pdf,:as => 'national_pdf'
      end  
    end
  end

  match '*a' => 'errors#routing' ,:via => [:get,:post,:delete,:patch,:post]

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
	belongs_to :company
  has_many :license_issue_activities
  validates :remarks, presence: true, :if => lambda{  !remarks.nil? }
  validates :description, presence: true, :if => lambda{  !description.nil? }
  include Workflow
  workflow do
    state :initiated do
      event :submit, :transitions_to => :pending
    end
    state :pending do
      event :ready_approval, :transitions_to => :awaiting_for_director_approval
    end
    state :awaiting_for_director_approval do
      event :director_accept, :transitions_to => :awaiting_for_minister_approval
      event :director_reject, :transitions_to => :director_has_rejected
    end
    state :awaiting_for_minister_approval do
      event :minister_reject, :transitions_to => :minister_has_rejected
      event :minister_accept, :transitions_to => :minister_has_accepted
    end
    state :minister_has_accepted do
      event :revoke, :transitions_to => :revoked
      event :issue_license, :transitions_to => :license_issued
    end
    state :license_issued do
      event :revoke, :transitions_to => :revoked
    end
    state :revoked do
      event :reinstate, :transitions_to => :reinstated
    end
    state :reinstated do
     event :issue_license, :transitions_to => :license_issued
      event :revoke, :transitions_to => :revoked
    end
    state :minister_has_rejected
  end

  def submit
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.status = 'initiated'
    l.save!
  end 

  def director_accept
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.remarks = remarks
    l.status = 'director has accepted'
    l.save!
  end 
  
  def director_reject
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.remarks = remarks
    l.status = 'director has rejected'
    l.save!
  end 

  def minister_accept
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.remarks = remarks
    l.status = 'minister has accepted'
    l.save!
  end 

  def minister_reject
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.remarks = remarks
    l.status = 'minister has rejected'
    l.save!
  end 

  def revoke
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.remarks = remarks
    l.status = 'revoked'
    l.save!
  end 

  def reinstate
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.remarks = remarks
    l.status = 'reinstated'
    l.save!
  end 

  def issue_license
    puts 'sending email to the author explaining the reason...'
    l = LicenseIssueActivity.new
    l.user_id = User.current.id
    l.certificate_id = id
    l.status = 'License Issued'
    l.save!
  end  
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_certificate, only: [:show, :edit, :update, :destroy,:ready_approval,:pending,:director_reject,:director_accept,:minister_reject,:minister_accept,:revoke,:reinstate,:issue_license]
  before_action :set_company
  #, only: [:index, :new, :edit, :create, :show, :update, :destroy,:director_reject,:director_accept,:minister_reject,:minister_accept]
  respond_to :html

  def index
    @certificates = @company.certificates
    respond_with(@certificates)
  end

  def show
   # respond_with(@certificate)
    respond_to do |format|
    format.html 
    format.pdf do
      img = "#{Rails.root}/app/assets/images/certificate.png"
      pdf = Prawn::Document.new(background: img, :page_size => [631,868], :margin => 0.5, :page_layout => :landscape)
      pdf.font "Times-Roman"
      pdf.draw_text @certificate.license_issue_code, :at => [200,368], :size => 20
      pdf.draw_text @company.name, :at => [200,329], :size => 20
      pdf.draw_text @certificate.description, :at => [200,305], :size => 20
      pdf.draw_text @certificate.cert_issue_date.to_date.strftime('%v'), :at => [140,280], :size => 20
      pdf.draw_text @certificate.cert_term_date.to_date.strftime('%v'), :at => [450,272], :size => 20
    
      
      
      pdf.draw_text @company.name, :at => [290,198], :size => 20
      pdf.draw_text @certificate.description, :at => [280,170], :size => 20
        pdf.draw_text @certificate.cert_issue_date.to_date.strftime('%v'), :at =>  [250,135], :size => 20
      pdf.draw_text @certificate.cert_term_date.to_date.strftime('%v'), :at => [600,130], :size => 20
      send_data pdf.render, filename: "mycertficate.pdf",
                      type: "application/pdf"
    end
  end
  end

  def new
    #@certificate = Certificate.new
    @certificate = @company.certificates.new
    respond_with(@certificate)
  end

  def edit
   # respond_with(@certificate)
   # edit_company_certificate_path
  end

  def create
    @certificate = @company.certificates.new(certificate_params)
    @certificate.user_id = current_user.id
    #@certificate.save
    #respond_with(@certificate)

    respond_to do |format|
      if @certificate.save
         @certificate.submit!
        #Notifier.send_email.deliver
        #ActionMailer::Base.mail(:from => "pbs@hypertechsolutions.com", :to => "prashanth.bsp@gmail.com", :subject => "test", :body => "test").deliver
        format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'Certficate was successfully created.') }
        format.xml  { render :xml => @certificate, :status => :created, :location => @certificate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @certificate.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

      # if params[:remarks].nil?  or  !params[:remarks].blank? 
        @certificate.update(certificate_params)
        if @certificate.update_attributes(certificate_params)
            if  params[:commit_director] == 'Accept License' 
                director_accept
            elsif  params[:commit_director] == 'Reject License'  
               director_reject
            elsif  params[:commit_minister] == 'Accept License'  
               minister_accept
            elsif  params[:commit_minister] == 'Reject License'  
               minister_reject   
            elsif  params[:commit_revoke] == 'Revoke License'  
               revoke   
            elsif  params[:commit_reinstate] == 'Reinstate License'  
               reinstate   
            else 
             respond_to do |format| 
                format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'Certificate was successfully updated.') }
                format.xml  { head :ok }
              end  
            end 
        else
          respond_to do |format| 
            if params[:remarks].nil? 
             format.html { render :action => "show" }
             format.xml  { render :xml => @certificate.errors, :status => :unprocessable_entity }
           else
            format.html { render :action => "edit" }
            format.xml  { render :xml => @certificate.errors, :status => :unprocessable_entity }
          end
         end 
        end 
      #else
      #respond_to do |format| 
      #  format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'Certificate was successfully updated.') }
      #  format.xml  { head :ok }
      #end  
      #end  
    end
 

  def destroy
    @certificate.destroy
    respond_with(@certificate)
  end
  
  def ready_approval
    if @certificate.ready_approval!
       @u = User.all
       @u.each do |director|
       if  director.has_role? :director
        puts director.email
         begin
            ActionMailer::Base.mail(:from =>'no-reply@hawlahaguud.com',:to => director.email, :subject => "Ministry of Public Works & Reconstruction of The Minister ", :body => "Hi #{director.username},awaiting your approval for license activity #{@certificate.description}").deliver
          rescue => e
            logger.warn "Unable to foo, will ignore: #{e}" 
          end
         end 
     end 
     respond_to do |format|
      format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'ready for approval success.') }
     end
   end  
  end
    
  def director_accept
    if @certificate.director_accept!
       @u = User.all
       @u.each do |minister|
       if  minister.has_role? :minister
         begin
            ActionMailer::Base.mail(:from =>'no-reply@hawlahaguud.com',:to => minister.email, :subject => "Ministry of Public Works & Reconstruction of The Minister ", :body => "Hi #{minister.username},awaiting your approval for license #{@certificate.description}").deliver
          rescue => e
            logger.warn "Unable to foo, will ignore: #{e}" 
          end
         end 
     end 
     respond_to do |format|
      format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'Director has accepted.') }
     end
   end
  end

  def director_reject
     if @certificate.director_reject!
       respond_to do |format|
          format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'Director has rejected.') }
       end 
     end   
  end

  def minister_accept
    if @certificate.minister_accept!
    @certificate.company.owners.each do |owner|
      begin
        ActionMailer::Base.mail(:from =>'no-reply@hawlahaguud.com',:to => owner.email, :subject => "Ministry of Public Works & Reconstruction of The Minister ", :body => "Hi #{owner.name},We have accepted your license for #{@certificate.description},please do contact us for more").deliver
      rescue => e
        logger.warn "Unable to foo, will ignore: #{e}" 
      end
    end
     respond_to do |format|
      format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'License is accepted.') }
     end
   end
  end

  def minister_reject
     if @certificate.minister_reject!
       @certificate.company.owners.each do |owner| 
         begin
          ActionMailer::Base.mail(:from =>'no-reply@hawlahaguud.com',:to => owner.email, :subject => "Ministry of Public Works & Reconstruction of The Minister ", :body => "Hi #{owner.name},Your license for #{@certificate.description} has been rejected,please do contact us for more").deliver
        rescue => e
          logger.warn "Unable to foo, will ignore: #{e}" 
        end
       end 
       respond_to do |format|
          format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'Rejected successfully.') }
       end 
     end   
  end

  def revoke
     if @certificate.revoke!
        @certificate.company.owners.each do |owner| 
         begin
          ActionMailer::Base.mail(:from =>'no-reply@hawlahaguud.com', :to => owner.email, :subject => "Ministry of Public Works & Reconstruction of The Minister ", :body => "Hi #{owner.name},Your license for #{@certificate.description} has been revoked/cancelled,please do contact us for more").deliver
        rescue => e
          logger.warn "Unable to foo, will ignore: #{e}" 
        end
      end
       respond_to do |format|
          format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'License is revoked.') }
       end 
     end   
  end

  def reinstate
     if @certificate.reinstate!
        @certificate.company.owners.each do |owner| 
         begin
           ActionMailer::Base.mail(:from =>'no-reply@hawlahaguud.com',:to => owner.email, :subject => "Ministry of Public Works & Reconstruction of The Minister ", :body => "Hi #{owner.name},Your license for #{@certificate.description} has been reinstated,please do contact us for more").deliver
        rescue => e
          logger.warn "Unable to foo, will ignore: #{e}" 
        end
      end
       respond_to do |format|
          format.html { redirect_to(company_certificate_path(@company,@certificate), :notice => 'License is reinstated.') }
       end 
     end   
  end

  def issue_license
     if @certificate.issue_license!
         @certificate.company.owners.each do |owner| 
          begin
           ActionMailer::Base.mail(:from =>'no-reply@hawlahaguud.com',:to => owner.email, :subject => "Ministry of Public Works & Reconstruction of The Minister ", :body => "Hi #{owner.name},Certificate for license  #{@certificate.description} has been generated,please do contact us for more").deliver
        rescue => e
          logger.warn "Unable to foo, will ignore: #{e}" 
        end
       end
       respond_to do |format|
          format.html { redirect_to(companies_path, :notice => 'License issued successfully.') }
       end 
     end   
  end
  private
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/edit.html.erb
<div class="row">
      <div class="span12 padding5">
        <div class="span3">
          
        <nav class="sidebar light">
    <ul>
        <li class="title">Admin Section</li>
        <li class="stick" data-no-turbolink >
         <%= link_to(company_certificates_path) do %>
            <i class="icon-arrow-left"></i>Dashboard</a>
          <% end %>
        </li>
        <li class="stick"><a href="#"><i class="icon-home"></i>Client Registration</a></li>
        <li class="stick"><a href="#"><i class="icon-newspaper"></i>Expired Certificates</a></li>
        <li class="stick"><a href="/pending_approve/list_all"><i class="icon-enter"></i>Pending To Approve</a></li>
    <li class="stick"><a href="#"><i class="icon-printer"></i>Print Actions</a></li>
    <li class="stick"><a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a></li>
    </ul>
</nav>
          
        </div>
        <div class="span9">
          <div class="panel">
              <div class="panel-content">
              	<legend>Edit License Form for :    <%= @company.name %> </legend>
			
		<%= render 'form' %>
		</div>
		 
    </div>
    </div>
  </div>
</div>
</div>  

app/views/certificates/index.html.erb
 <div class="row">
      <div class="span10 padding5">
        <div class="span3">
          
        <nav class="sidebar light">
    <ul>
        <li class="title">Admin Section</li>
         <li class="stick" data-no-turbolink >
         <%= link_to(companies_path) do %>
          <i class="icon-arrow-left"></i>Back</a>
         <% end %> 
           </li>
        <li class="stick">
          <%= link_to(new_company_certificate_path) do %>
             <i class="icon-new"></i> New License Form
          <% end %>
        </li>
        <li class="stick"><a href="#"><i class="icon-home"></i>Client Registration</a></li>
        <li class="stick"><a href="#"><i class="icon-newspaper"></i>Expired Certificates</a></li>
        <li class="stick"><a href="/pending_approve/list_all"><i class="icon-enter"></i>Pending To Approve</a></li>
    <li class="stick"><a href="#"><i class="icon-printer"></i>Print Actions</a></li>
    <li class="stick"><a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a></li>
    </ul>
</nav>
          
        </div>
        <div class="span9">
          <div class="panel2">
              <div class="panel-content">
                <table class="table hovered">
  <thead>
    <tr>
      <th class="size2 text-left">License Activities</th>
     <!-- <th class="size2 text-left">Issue Date</th> -->
      <th class="size3 text-left">Eff Date</th>
      <th class="size2 text-left">Expire Date</th>
      <th class="size2 text-left">Status</th>
      <th colspan="4" class="size4">Actions</th>
    </tr>
  </thead>
    <tbody>
      <% @certificates.each do |certificate| %>
        <tr>
          <td><%= certificate.description %></td>
         <!-- <td><%= certificate.cert_issue_date.to_date %></td>-->
           <td><%= certificate.cert_eff_date.to_date %></td>
            <td><%= certificate.cert_term_date.to_date %></td>
             <td><%= certificate.workflow_state %></td>
        <td class="right">
           <table>
        <!--    <td>
          <%= link_to(company_certificate_path(@company,certificate)) do %>
              <button class="small info">View</button>
          <% end %>
         </td> -->
         
         
          <% if certificate.awaiting_director_approval? %> 
          <% if can? :update, certificate %>
           <td class="right">
             <%= link_to(edit_company_certificate_path(@company,certificate)) do %>
                <button class="small default">Edit</button>
            </td> 
            <% end %>
          <% end %>
        <% end %>
         
        
          <% if certificate.minister_accepted? %> 
           <% if can? :issue, certificate %>
           <td class="right" nowrap="nowrap">
             <%= link_to(company_certificate_path(@company,certificate,:pdf )) do %>
                <button class="small success">Issue Certificate</button>
              <% end %>
               </td> 
            <% end %>   
          <% end %>

        <!--  <% if certificate.awaiting_director_approval? %> 
        
            <% if can? :director_accept, certificate %>
               <td class="right">
              <%= link_to(director_accept_company_certificate_path(@company,certificate)) do %>
               <button class="small success">Accept</button>
              </td> 
              <% end %>
           
             <% end %>
          
           <% if can? :director_reject, certificate %> 
             <td class="right">
            <%= link_to(director_reject_company_certificate_path(@company,certificate)) do %>
               <button class="small danger">Reject</button>
            <% end %>
             </td> 
          <% end %>
        <% end %>
           <% if certificate.awaiting_minister_approval? %> 
            <% if can? :minister_accept, certificate %> 
             <td class="right">
              <%= link_to(minister_accept_company_certificate_path(@company,certificate)) do %>
              <button class="small success">Accept</button>
            <% end %>
            </td> 
          <% end %>

          <% if can? :minister_reject, certificate %> 
           <td class="right">
            <%= link_to(minister_reject_company_certificate_path(@company,certificate)) do %>
                <button class="small success">Reject</button>
            <% end %>
            </td> 
          <% end %> 
          <% end %> -->
        </tr>
      </table>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>

       </div>
            </div>
        </div>
        </div>
      </div>

  <!--</div>
         <%= link_to(companies_path, class: "btn btn-success") do %>
            Back
          <% end %>
          <%= link_to(new_company_certificate_path, class: "btn btn-success") do %>
            Create New Certficate
          <% end %>
    </div>
   </div>
</div>-->

app/views/certificates/new.html.erb
<div class="row">
      <div class="span12 padding5">
        <div class="span3">
          
        <nav class="sidebar light">
    <ul>
        <li class="title">Admin Section</li>
        <li class="stick" data-no-turbolink >
         <%= link_to(company_certificates_path) do %>
            <i class="icon-arrow-left"></i>Back</a>
          <% end %>
        </li>
        <li class="stick"><a href="#"><i class="icon-home"></i>Client Registration</a></li>
        <li class="stick"><a href="#"><i class="icon-newspaper"></i>Expired Certificates</a></li>
        <li class="stick"><a href="/pending_approve/list_all"><i class="icon-enter"></i>Pending To Approve</a></li>
    <li class="stick"><a href="#"><i class="icon-printer"></i>Print Actions</a></li>
    <li class="stick"><a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a></li>
    </ul>
</nav>
          
        </div>
        <div class="span9">
          <div class="panel">
              <div class="panel-content">
                <legend>New License Form for :    <%= @company.name %> </legend>
		<%= render 'form' %>
	     </div>
    </div>
  </div>
</div>
</div>  

app/views/certificates/show.html.erb
<div class="row">
      <div class="span12 padding5">
        <div class="span3">
          
        <nav class="sidebar light">
    <ul>
        <li class="title">Admin Section</li>
        <li class="stick" data-no-turbolink >
        <%= link_to(companies_path) do %>
          <i class="icon-arrow-left"></i>Dashboard</a>
         <% end %> 
       </li>
       <% if  current_user.has_role? :staff and  !@certificate.license_issued?%>
        <li class="stick">
         <%= link_to(edit_company_path(@company)) do %>
           <i class="icon-wrench"></i> Edit Client Registration
          <% end %>
        </li>
        <% end %>
        <li class="stick"><a href="#"><i class="icon-newspaper"></i>Expired Certificates</a></li>
        <li class="stick"><a href="/pending_approve/list_all"><i class="icon-enter"></i>Pending To Approve</a></li>
    <li class="stick"><a href="#"><i class="icon-printer"></i>Print Actions</a></li>
    <li class="stick"><a href="/customer_lookups/search" class="element"><i class="icon-user-3"></i>Customers Lookup</a></li>
    </ul>
</nav>
          
        </div>
        <div class="span9">
          <div class="panel">
              <div class="panel-content">
                <% if @certificate.errors.any? %>
                  <div id="error_explanation">
                    <h2>
                      <%= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:" %>
                    </h2>
                    <ul>
                      <% @certificate.errors.full_messages.each do |msg| %>
                        <li>
                          <%= msg %>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                  <% end %>
                   <%= render  "companies/show" %>
                    <table class="table">
                 <thead>
                   <tr class="info">
                      <td class="text-left" colspan="4">License Activities </td>
                  </tr>
                  <tr>
                      <th class="text-left">Date</th>
                      <th class="text-left">User Email</th>
                      <th class="text-left">Status</th>
                      <th class="text-center">Remarks</th>
                  </tr>
                </thead>
                <tbody>
                  <% @certificate.license_issue_activities.each do |license_activity| %>
                     <tr>
                        <td class="text-left">
                         <%= license_activity.created_at.strftime('%v %r') %>
                       </td>  
                        <td class="text-left">
                         <%=license_activity.user.email%>
                       </td>  
                      <td class="text-left">
                         <%= license_activity.status %>
                       </td>   
                      <td class="text-left">
                           <%=license_activity.remarks%>
                       </td>  
                     </tr>
                  <% end %>
                </tbody>
                </table>  
   <%= form_for [@company, @certificate]  do |f| %>
                <table class="table">
                   <tr class="info">
                      <td class="text-left" colspan="2">
                          License Information
                       </td>   
                    </tr>  

                     <tr>
                      <td class="text-left span3">
                          License Activities:
                       </td>   
                       <td class="text-left ">
                         <%= @certificate.description %>
                       </td>  
                     </tr>  
                    <tr>
                      <td class="text-left">
                          License Status:
                       </td>   
                       <td class="text-left">
                         <%= @certificate.workflow_state %>
                       </td>  
                     </tr>     
                    <tr>
                      <td class="text-left">
                         Certficate Issue Date:
                       </td>   
                       <td class="text-left">
                         <%= @certificate.cert_issue_date.to_date.strftime('%v') %>
                       </td>  
                     </tr>  
                      <tr>
                      <td class="text-left">
                        Certficate Effective Date:
                       </td>   
                       <td class="text-left">
                         <%= @certificate.cert_eff_date.to_date.strftime('%v') %>
                       </td>  
                     </tr>  
                     <tr>
                      <td class="text-left">
                       Certficate Expire Date:
                       </td>   
                       <td class="text-left">
                           <%= @certificate.cert_term_date.to_date.strftime('%v') %>
                       </td>  
                     </tr> 

                     <% if !(current_user.has_role? :admin or current_user.has_role? :super_admin) %>

                       <% if (current_user.has_role? :director and @certificate.awaiting_for_director_approval?) or (current_user.has_role? :minister and  @certificate.awaiting_for_minister_approval?) or (current_user.has_role? :minister and @certificate.minister_has_accepted?)   or (current_user.has_role? :minister and @certificate.revoked?) or 
                         (current_user.has_role? :minister and @certificate.license_issued?) or
                         (current_user.has_role? :minister and @certificate.reinstated?) %> 
                     <tr>
                      <td class="text-left">
                      Remarks:
                       </td>   
                       <td class="text-left">
                          <div class="input-control textarea size6" data-role="input-control">
                           <%= f.text_area :remarks,:value => '', :as => :text, :input_html => { :rows => 4, :cols => 20 },:placeholder=>"Enter Remarks" %>
                         </div>
                       </td>  
                     </tr> 
                    <% end %>
                     <% if @certificate.awaiting_for_director_approval? %> 
                      <tr>
                        <% if can? :director_accept, @certificate %>
                           <td class=" right">
                           <input name="commit_director" data-disable-with="Processing." class="success default" type="submit" value="Accept License">     
                        </td> 
                         <% end %>
                      
                       <% if false and can? :director_reject, @certificate %> 
                         <td class="right">
                           <input name="commit_director" data-disable-with="Processing." class="small danger" type="submit" value="Reject License">
                         </td> 
                           <% end %>
                       <% end %>

                  <% if @certificate.awaiting_for_minister_approval? %> 
                      <tr>
                        <% if can? :minister_accept, @certificate %>
                           <td class="right">
                             <input name="commit_minister" data-disable-with="Processing." class="success default" type="submit" value="Accept License">   
                           </td> 
                         <% end %>
                      
                       <% if can? :minister_reject, @certificate %> 
                         <td class="right">
                           <input name="commit_minister" data-disable-with="Processing." class="small danger" type="submit" value="Reject License">
                         </td> 
                           <% end %>
                          </tr> 
                  <% end %>

                        <% if (@certificate.minister_has_accepted? or @certificate.reinstated? or @certificate.license_issued? ) and current_user.has_role? :minister %> 
                        <tr>
                           <td class="right">
                             <input name="commit_revoke" data-disable-with="Processing." class="small danger" type="submit" value="Revoke License">
                           </td> 
                      
                          </tr> 
                       <% end %>
                    <% if @certificate.revoked? and current_user.has_role? :minister  %> 
                         <tr>
                           <td class="right">
                             <input name="commit_reinstate" data-disable-with="Processing." class="small danger" type="submit" value="Reinstate License">
                           </td> 
                           </tr>  
                    <% end %> 
                 <% if @certificate.pending? and can? :ready_for_approval, @certificate%> 
                 <tr>
                    <td class="right">
                    <%= link_to(ready_approval_company_certificate_path(@company,@certificate)) do %>
                      <button class="small success " data-disable-with="Processing.">Ready for approval</button>
                    <% end %>
                  </td>
                </tr>
               <% end %>
                <% end %>
                           </table>   
             <% end %>
                </div>
            </div>
          </div>
        </div>